const bookTypes = [
  "---Select One---",
  "Action and Adventure",
  "Art & Photography",
  "Biography or Autobiography",
  "Children's",
  "Classic",
  "Comic Book or Graphic Novel",
  "Contemporary Fiction",
  "Cookbook",
  "Detective and Mystery",
  "Essay",
  "Fantasy",
  "Guide / How-to",
  "Historical Fiction",
  "History",
  "Horror",
  "Humanities & Social Sciences",
  "Humor",
  "Literary Fiction",
  "Memoir",
  "Manga - Shonen",
  "Manga - Shojo",
  "Manga - Seinen",
  "Manga - Josei",
  "Manga - Kodomomuke",
  "Parenting & Families",
  "Poetry",
  "Religion & Spirituality",
  "Romance",
  "Science & Technology",
  "Science Fiction (Sci-Fi)",
  "Self-Help",
  "Short Story",
  "Suspense and Thriller",
  "Travel",
  "True Crime",
  "Women's Fiction",
  "Young Adult",
];

export default bookTypes;
